# Site settings
title: Slijpservice Heiloo
email: slijpserviceheiloo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Gereedschappen slijpen. Boren, frezen. Ook schaatsen slijpen!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://slijpservice-heiloo.nl" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
